#
AWSTemplateFormatVersion: 2010-09-09
Description: "This template launches a Windows 2019 server and installs and configures a custom IIS site in the ap-southeast-2 region."
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - SubnetId
          - SecurityGroupID
      -
        Label:
          default: "Instance Configuration"
        Parameters:
          - KeyID
Parameters:
  SubnetId:
    Description: Select Subnet
    Type: "AWS::EC2::Subnet::Id"
  SecurityGroupID:
    Description: Select Security Groups
    Type: "AWS::EC2::SecurityGroup::Id"
  KeyID:
    Description: Select Public Key
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0fb8890c7a7ca1457    # This AMI id is for the AP-SOUTHEAST-2 Region.  Update this to the relevant AMI ID for other regions
      KeyName: !Ref KeyID
      UserData:
        'Fn::Base64':
          !Sub |
            <powershell>
            Import-Module ServerManager;
            Install-WindowsFeature Web-Server -IncludeManagementTools -IncludeAllSubFeature
            remove-item -recurse c:\inetpub\wwwroot\*
            (New-Object System.Net.WebClient).DownloadFile("https://immersionday-labs.s3.amazonaws.com/ec2-windows.zip", "c:\inetpub\wwwroot\ec2-windows.zip")

            $shell = new-object -com shell.application
            $zip = $shell.NameSpace("c:\inetpub\wwwroot\ec2-windows.zip")
            foreach($item in $zip.items())
            {
              $shell.Namespace("c:\inetpub\wwwroot\").copyhere($item)
            }
            Start-Process "iisreset.exe" -NoNewWindow -Wait

            Import-Module NetSecurity;
            Set-NetFirewallRule -DisplayName "File and Printer Sharing (Echo Request - ICMPv4-In)" -enabled True
            </powershell>
      Tags:
        - Key: Name
          Value: My EC2 Instance
      SecurityGroupIds: !Split
        - ','
        - !Join
          - ','
          -  - !Ref SecurityGroupID
      SubnetId: !Ref SubnetId
  EIpAddress:
    Type: AWS::EC2::EIP
  EIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'Ec2Instance'
      EIP: !Ref 'EIpAddress'
Outputs:
  InstanceId:
    Description: InstanceID of the new EC2 Instance.
    Value: !Ref 'Ec2Instance'
  InstanceIpAddress:
    Description: Public IP Address of the EC2 Instance.
    Value: !Ref 'EIpAddress'