AWSTemplateFormatVersion: 2010-09-09
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0119aa4d67e59007c
      UserData:
        'Fn::Base64':
          !Sub |
            #include
            https://s3.amazonaws.com/immersionday-labs/bootstrap.sh
      Tags:
        - Key: Name
          Value: My EC2 Instance
      SecurityGroupIds:
        - sg-0dce1cbd2b76f0c59
      SubnetId: subnet-092cd96fbbbad61bb
  EIpAddress:
    Type: AWS::EC2::EIP
  EIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'Ec2Instance'
      EIP: !Ref 'EIpAddress'
Outputs:
  InstanceId:
    Description: InstanceID of the new EC2 Instance.
    Value: !Ref 'Ec2Instance'
  InstanceIpAddress:
    Description: Public IP Address of the EC2 Instance.
    Value: !Ref 'EIpAddress'