AWSTemplateFormatVersion: 2010-09-09
Description: "This template launches an Amazon Linux EC2 instance and attaches a 100GB disk in the ap-southeast-2 region."
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - SubnetId
          - SecurityGroupID
      -
        Label:
          default: "Instance Configuration"
        Parameters:
          - KeyID
Parameters:
  SubnetId:
    Description: Select Subnet
    Type: "AWS::EC2::Subnet::Id"
  SecurityGroupID:
    Description: Select Security Groups
    Type: "AWS::EC2::SecurityGroup::Id"
  KeyID:
    Description: Select Public Key
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0119aa4d67e59007c
      KeyName: !Ref KeyID
      Tags:
        - Key: Name
          Value: My EC2 Instance
      SecurityGroupIds: !Split
        - ','
        - !Join
          - ','
          -  - !Ref SecurityGroupID
      SubnetId: !Ref SubnetId
      BlockDeviceMappings:
        - DeviceName: /dev/sdf
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 100
  EIpAddress:
    Type: AWS::EC2::EIP
  EIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'Ec2Instance'
      EIP: !Ref 'EIpAddress'
Outputs:
  InstanceId:
    Description: InstanceID of the new EC2 Instance.
    Value: !Ref 'Ec2Instance'
  InstanceIpAddress:
    Description: Public IP Address of the EC2 Instance.
    Value: !Ref 'EIpAddress'